/**
 * @file Ffmpeg.c
 * @author your name (you@domain.com)
 * @brief 
 * @version 0.1
 * @date 2021-01-22
 * 
 * @copyright Copyright (c) 2021
 * 
 */

#include "HAP.h"
#include "HAPBase.h"

#include "App_Camera.h"
#include "App.h"
#include "DB.h"
#include "streaming.h"
#include <arpa/inet.h>
#include "External/Base64/util_base64.h"

HAPError createCommand(void* context){
    AccessoryContext* myContext = context;
    streamingSession* mySession = &myContext->session;
    const char accessoryAddress[INET_ADDRSTRLEN];
    (void*) inet_ntop(AF_INET, &mySession->controllerAddress.ipAddress, accessoryAddress, INET_ADDRSTRLEN );
    uint8_t ssrcBuffer[KEYLENGTH + SALTLENGTH];
    HAPRawBufferCopyBytes(ssrcBuffer, mySession->videoParams.srtpMasterKey, KEYLENGTH);
    HAPRawBufferCopyBytes(ssrcBuffer[UUIDLENGTH], mySession->videoParams.srtpMasterSalt, SALTLENGTH);
    size_t ssrc64bufferLength = util_base64_encoded_len(sizeof(ssrcBuffer));
    size_t* ssrc64length;
    char ssrc64[ssrc64bufferLength];
    util_base64_encode(ssrcBuffer, sizeof(ssrcBuffer), ssrc64, ssrc64bufferLength, ssrc64length);

    HAPStringBuilderRef stringBuilder;
    char stringBuffer[1024];
    HAPStringBuilderCreate(&stringBuilder, stringBuffer, 1024);
    
    HAPStringBuilderAppend(&stringBuilder,
    "/usr/bin/ffmpeg -re -f avfoundation -framerate %d -i 0:0 -threads 0 \
    -vcodec libx264 -an -pix_fmt yuv420p -r %d -f rawvideo -tune zerolatency \
    -vf scale=%lu:%lu -b:v %lu -bufsize %lu -payload_type %d -ssrc %lu -f rtp \
    -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params %s \
    srtp://%s:%lu?rtcpport=%lu&localrtcpport=%lu&pkt_size=&lu",
    mySession->videoParameters.codecConfig.videoAttributes.frameRate,
    mySession->videoParameters.codecConfig.videoAttributes.frameRate,
    mySession->videoParameters.codecConfig.videoAttributes.imageWidth,
    mySession->videoParameters.codecConfig.videoAttributes.imageHeight,
    mySession->videoParameters.vRtpParameters.vRtpParameters.maximumBitrate, // -b:v
    mySession->videoParameters.vRtpParameters.vRtpParameters.maximumBitrate, //bufsize
    mySession->videoParameters.vRtpParameters.vRtpParameters.payloadType,
    mySession->videoParameters.vRtpParameters.vRtpParameters.ssrc,
    ssrc64, // base64 encode key+salt
    accessoryAddress,
    mySession->controllerAddress.videoPort, //remote
    mySession->controllerAddress.videoPort, //rtcp
    mySession->controllerAddress.videoPort, //local
    mySession->videoParameters.vRtpParameters.maxMTU
    );
}

/* Borrowed from HAP-python until I figure it out
        :param session_info: Contains information about the current session. Can be used
            for session storage. Available keys:
            - id - The session ID.
        :type session_info: ``dict``
        :param stream_config: Stream configuration, as negotiated with the HAP client.
            Implementations can only use part of these. Available keys:
            General configuration:
                - address - The IP address from which the camera will stream
                - v_port - Remote port to which to stream video
                - v_srtp_key - Base64-encoded key and salt value for the
                    AES_CM_128_HMAC_SHA1_80 cipher to use when streaming video.
                    The key and the salt are concatenated before encoding
                - a_port - Remote audio port to which to stream audio
                - a_srtp_key - As v_srtp_params, but for the audio stream.
            Video configuration:
                - v_profile_id - The profile ID for the H.264 codec, e.g. baseline.
                    Refer to ``VIDEO_CODEC_PARAM_PROFILE_ID_TYPES``.
                - v_level - The level in the profile ID, e.g. 3:1.
                    Refer to ``VIDEO_CODEC_PARAM_LEVEL_TYPES``.
                - width - Video width
                - height - Video height
                - fps - Video frame rate
                - v_ssrc - Video synchronisation source
                - v_payload_type - Type of the video codec
                - v_max_bitrate - Maximum bit rate generated by the codec in kbps
                    and averaged over 1 second
                - v_rtcp_interval - Minimum RTCP interval in seconds
                - v_max_mtu - MTU that the IP camera must use to transmit
                    Video RTP packets.
            Audio configuration:
                - a_bitrate - Whether the bitrate is variable or constant
                - a_codec - Audio codec
                - a_comfort_noise - Wheter to use a comfort noise codec
                - a_channel - Number of audio channels
                - a_sample_rate - Audio sample rate in KHz
                - a_packet_time - Length of time represented by the media in a packet
                - a_ssrc - Audio synchronisation source
                - a_payload_type - Type of the audio codec
                - a_max_bitrate - Maximum bit rate generated by the codec in kbps
                    and averaged over 1 second
                - a_rtcp_interval - Minimum RTCP interval in seconds
                - a_comfort_payload_type - The type of codec for comfort noise

FFMPEG_CMD = (
    # pylint: disable=bad-continuation
    'ffmpeg -re -f avfoundation -framerate {fps} -i 0:0 -threads 0 '
    '-vcodec libx264 -an -pix_fmt yuv420p -r {fps} -f rawvideo -tune zerolatency '
    '-vf scale={width}:{height} -b:v {v_max_bitrate}k -bufsize {v_max_bitrate}k '
    '-payload_type 99 -ssrc {v_ssrc} -f rtp '
    '-srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params {v_srtp_key} '
    'srtp://{address}:{v_port}?rtcpport={v_port}&'
    'localrtcpport={v_port}&pkt_size=1378'
)
'''Template for the ffmpeg command.'''
*/